#Increase OSX default docker size link:
#https://forums.docker.com/t/increase-docker-container-disk-space-on-os-x/26725/2

#--------COLORES ESCAPE CODES------------
#for i in `seq 1 100`; do printf "\033[48;5;${i}m${i} "; done
#NC='\033[0m' # No Color
#Black="\033[0;30m";             White="\033[1;37m"
#Red="\033[0;31m";               LightRed="\033[1;31m"
#Green="\033[0;32m";             LightGreen="\033[1;32m"
#BrownOrange="\033[0;33m";       Yellow="\033[1;33m"
#Blue="\033[0;34m";              LightBlue="\033[1;34m"
#Purple="\033[0;35m";            LightPurple="\033[1;35m"
#Cyan="\033[0;36m";              LightCyan="\033[1;36m"
#LightGray="\033[0;37m";         DarkGray="\033[1;30m"
#BlackOnGreen="\033[30;48;5;82m"
#WhiteOnBurg="\033[30;48;5;88m"
#
#BoldWhiteOnRed="\033[1;1;5;41m"
#BoldWhiteOnGreen="\033[1;1;5;42m"
#BoldWhiteOnYellow="\033[1;1;5;43m"
#BoldWhiteOnBlue="\033[1;1;5;44m"
#BoldWhiteOnPink="\033[1;1;5;45m"
#BoldWhiteOnTurquoise="\033[1;1;5;46m"

#BoldYellowOnBlue="\033[1;33;44m"
#BoldYellowOnPurple="\033[1;33;44m"


FROM debian:jessie
MAINTAINER mhassan@splunk.com version: 0.1
ENV DEBIAN_FRONTEND noninteractive
ENV TERM linux

ENV SPLUNK_PRODUCT splunk

ENV SPLUNK_VERSION 7.0.0
ENV SPLUNK_BUILD c8a78efdd40f

ENV SPLUNK_FILENAME splunk-${SPLUNK_VERSION}-${SPLUNK_BUILD}-Linux-x86_64.tgz
ENV SPLUNK_HOME /opt/splunk
ENV SPLUNK_GROUP splunk
ENV SPLUNK_USER splunk
ENV SPLUNK_BACKUP_DEFAULT_ETC /var/opt/splunk


RUN printf "\033[1;33m\n\n-------------------- Installing Misc Stuff ---------------------\n"
RUN apt-get -qq update && printf "\033[1;33m]"
RUN apt-get -qq install -y wget apt-utils && apt-get -qq update
RUN apt-get -qq install -y sudo vim net-tools telnet dnsutils
RUN apt-get -qq update && printf "\033[1;33m]"
COPY containers.bashrc /root/.bashrc
COPY containers.vimrc /root/.vimrc

RUN printf "\033[1;32m\n\n-------------------- Installing Splunk ---------------------\n"
# add splunk:splunk user
RUN groupadd -r ${SPLUNK_GROUP} \
    && useradd -r -m -g ${SPLUNK_GROUP} ${SPLUNK_USER}
# make the "en_US.UTF-8" locale so splunk will be utf-8 enabled by default
RUN apt-get -qq install -y locales \
    && localedef -i en_US -c -f UTF-8 -A /usr/share/locale/locale.alias en_US.UTF-8
ENV LANG en_US.utf8

# pdfgen dependency
RUN apt-get -qq install -y libgssapi-krb5-2

# Download official Splunk release, verify checksum and unzip in /opt/splunk
# Also backup etc folder, so it will be later copied to the linked volume
RUN mkdir -p ${SPLUNK_HOME} \
    && wget -qO /tmp/${SPLUNK_FILENAME} https://download.splunk.com/products/${SPLUNK_PRODUCT}/releases/${SPLUNK_VERSION}/linux/${SPLUNK_FILENAME} \
    && wget -qO /tmp/${SPLUNK_FILENAME}.md5 https://download.splunk.com/products/${SPLUNK_PRODUCT}/releases/${SPLUNK_VERSION}/linux/${SPLUNK_FILENAME}.md5 \
    && (cd /tmp && md5sum -c ${SPLUNK_FILENAME}.md5) \
    && tar xzf /tmp/${SPLUNK_FILENAME} --strip 1 -C ${SPLUNK_HOME} \
    && rm /tmp/${SPLUNK_FILENAME} \
    && rm /tmp/${SPLUNK_FILENAME}.md5 \
    && mkdir -p /var/opt/splunk \
    && cp -R ${SPLUNK_HOME}/etc ${SPLUNK_BACKUP_DEFAULT_ETC} \
    && rm -fR ${SPLUNK_HOME}/etc \
    && chown -R ${SPLUNK_USER}:${SPLUNK_GROUP} ${SPLUNK_HOME} \
    && chown -R ${SPLUNK_USER}:${SPLUNK_GROUP} ${SPLUNK_BACKUP_DEFAULT_ETC} \
    && rm -rf /var/lib/apt/lists/*
#    && apt-get purge -y --auto-remove wget \
COPY splunk_web_conf.sh /sbin/splunk_web_conf.sh
RUN chmod +x /sbin/splunk_web_conf.sh
#--------------------------------------------------------------

RUN printf "\033[1;36m\n\n-------------------- Installing supervisord ---------------------\n"
RUN apt-get -qq update && printf "\033[1;36m]"
RUN apt-get -qq install -y supervisor
#--------------------------------------------------------------

#RUN rm -f /tmp/hadoop-2.9.0.tar.gz /tmp/Hunkdata.json.gz
# deleting wold.sql is done later on inside startup_mysql.sh after the import is finished
#RUN tar -xvf /tmp/local.tar /opt/splunk/etc/apps/splunk_app_db_connect/local/

#startup scripts with be kicked off from supervisord.conf
COPY startup_splunk.sh /sbin/startup_splunk.sh
RUN chmod +x /sbin/startup_splunk.sh
COPY startup_mysql.sh /sbin/startup_mysql.sh
RUN chmod +x /sbin/startup_mysql.sh
COPY startup_hadoop.sh /sbin/startup_hadoop.sh
RUN chmod +x /sbin/startup_hadoop.sh

# Copy new license
#COPY ./Splunk_Enterprise_Q3FY17.lic /var/opt/splunk/etc/licenses/download-trial/Splunk_Enterprise_Q3FY17.lic

# Ports Splunk Web, Splunk Daemon, KVStore, Splunk Indexing Port, Network Input, HTTP Event Collector
EXPOSE 8000/tcp 8089/tcp 8191/tcp 9997/tcp 1514/udp 8088/tcp
#MySQL
EXPOSE 3306/tcp
#Hadoop: Resource mgr:8088  namednode:50070  hdfs:9000
EXPOSE 50070/tcp 9000/tcp 8088/tcp 2122/tcp
# Hdfs ports
EXPOSE 50010 50020 50070 50075 50090 8020 9000
# Mapred ports
EXPOSE 10020 19888
#Yarn ports
EXPOSE 8030 8031 8032 8033 8040 8042 8088
#Other ports
EXPOSE 49707 2122

WORKDIR /opt/splunk

# Configurations folder, var folder for everything (indexes, logs, kvstore)
VOLUME [ "/opt/splunk/etc", "/opt/splunk/var", "/var/lib/mysql" ]

COPY supervisord.conf /etc/supervisor/supervisord.conf
CMD ["/usr/bin/supervisord"]


RUN printf "\033[1;33m\n\n-------------------- We are done baby! ---------------------\033[0m\n"


